-- DDL generated by Postico 2.0.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "User" (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username character varying(30) NOT NULL,
    password character varying(40),
    role_id integer NOT NULL DEFAULT 1 REFERENCES "Role"(id),
    owned_courses integer[],
    achievements integer[],
    age integer NOT NULL DEFAULT 11
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "User_pkey" ON "User"(id int4_ops);
