-- DDL generated by Postico 2.0.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "Achievement" (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name character varying(60),
    description character varying(110)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "Achievement_pkey" ON "Achievement"(id int4_ops);
